[versions]
hiddenapibypass = "6.1"
shizuku = "13.1.5"
material = "1.11.0"

[libraries]
shizuku-api = { module = "dev.rikka.shizuku:api", version.ref = "shizuku" }
shizuku-provider = { module = "dev.rikka.shizuku:provider", version.ref = "shizuku" }
hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapibypass" }
material = { module = "com.google.android.material:material", version.ref = "material" }
